### ISSUE TITLE
Please add more examples to cover all the API

### ISSUE THREAD

**Issue by abforce** [Softmotions/iowow#26]
I've been using iowow on Android but have a hard time to iterate all entries. I assume I should use `iwkv_cursor_open` but have no idea how to allocate the `IWKV_cursor`.

**Comment by adamansky** [comment]
Hi Ali! Take a look into some cursor tests, for example https://github.com/Softmotions/iowow/blob/master/src/kv/tests/iwkv_test1.c#L459 and https://github.com/Softmotions/iowow/blob/master/src/kv/iwkv.h#L395  It should help you. Of course more examples are needed, will keep this issue open until cursor examples.

**Comment by adamansky** [comment]
* Added cursors and compound keys example
https://github.com/Softmotions/iowow/blob/master/src/kv/examples
