### ISSUE TITLE
iwkv_open assertion fail on opening garbage file

### ISSUE THREAD

**Issue by pavelxdd** [Softmotions/iowow#29]
If the file is corrupted, `iwkv_open` crashes my application.

Create a garbage file:
```
dd bs=1024 count=10 </dev/urandom >file.db
```

Open it with iowow and see:
```
iwfsmfile.c:1302: 74005|0|Invalid file metadata. (IWFS_ERROR_INVALID_FILEMETA)|: Invalid file magic number

iwfsmfile.c:443: _fsm_blk_allocate_aligned_lw: Assertion `impl && impl->fsm && length_blk > 0' failed.
```

I expect that `iwkv_open` will return the error code, so that my application would continue running.
The library should never abort the host application in my opinion.

---

If build `iowow` in Release mode, then I just get segmentation fault.

**Comment by adamansky** [comment]
Good, will fix it shortly

**Comment by adamansky** [comment]
```
iowow (1.3.29) UNRELEASED; urgency=medium
  * FIXED iwkv_open assertion fail on opening garbage file #29
```
