### ISSUE TITLE
How to iterate over a db having compound keys?

### ISSUE THREAD

**Issue by abforce** [Softmotions/iowow#31]
I have a db with string keys and for each key I need to store 3 properties. For example "personal ID" as the key and 3 props "age", "phone" and "address" as its properties. To store the data in database, I created a DB with compound keys enabled. The "personal ID" is the main key and other props are numeric compound keys. Two questions:

1. How can I iterate the main keys and then retrieve its compound keys' values? i.e. "personal ID"s

2. How are databases having compound keys stored on the disk? Is the main key duplicated for each sub-key?

**Comment by adamansky** [comment]
Added compound keys example https://github.com/Softmotions/iowow/blob/master/src/kv/examples/compoundkeys1.c

Note: for compound keys last part of key must of integer type
