### ISSUE TITLE
pool performance when access by multi thread

### ISSUE THREAD

**Issue by dengdui-ganan** [Softmotions/iowow#32]
Hi： 
      I test the performance as follows:
          single thread access single iwdb:  get 20w qps
          multi thread  access single iwdb:  get 10w  qps 
          multi thread  access multi  iwdb:   get 10w qps 
     Multi thread can't speed read with iwdb? 
     Or what should i care when use iwdb?

**Comment by adamansky** [comment]
Hi! Could you please provide test code. Iowow uses RW locks so has good read scalability on SSD.

**Comment by dengdui-ganan** [comment]
I use iowow in kkv search, with first key as dbid, code as:
`IWKKVImpl::Get( const ACHData * pkey, const ACHData * skey_list, ACHData * val_list, int32_t & num ) {
	IWDB* db = get_db( pkey );
	if ( NULL == db )
	{
		return(ACHStatus( ACHStatus::ACH_DB_MISSED, "Fail to get db" ) );
	}
	IWKV_val	iw_key, iw_val;
	int32_t		succ = 0;
	for ( int32_t i = 0; i < num; ++i )
	{
		iw_key.data	= skey_list[i].get_data();
		iw_key.size	= skey_list[i].get_len();
		ACHData & val = val_list[i];
		if ( iwkv_get( *db, &iw_key, &iw_val ) )
		{
			val.set_data( NULL );
			val.set_len( 0 );
		} else {
			val.set_data( new char[iw_val.size] );
			val.set_len( iw_val.size );
			/* memcpy(val.get_data(), iw_val.data, iw_val.size); */
			succ += 1;
		}
	}`
  and perf test code with search function:
  `void search(int32_t num) {
    ACHData pkey;
    ACHData* skey_list = new ACHData[g_Skey_Num];
    ACHData* val_list = new ACHData[g_Skey_Num];
    create_key(skey_list);
    timeval start;
    gettimeofday(&start, NULL);
    int32_t count = 10;
    int32_t rnum = g_Skey_Num;
    while (count-- > 0) {
        for (int32_t i = 100 * num; i < 101 * (num + 1); ++i) {
            pkey.set_data((void*)(&i));
            pkey.set_len(sizeof(int32_t));
            g_impl.Get(&pkey, skey_list, val_list, rnum);
        }
    }
    timeval end;
    gettimeofday(&end, NULL);
}`
    with main function: 
`    std::vector<std::thread*> thread_vec;
    for (int32_t i = 0; i < thread_num; ++i) {
        std::thread* thread = new std::thread(search, i);
        thread_vec.push_back(thread);
    }
   for (auto thread: thread_vec) {thread->join();}
`
   Insert data before search, and test performance with different thread num.

**Comment by adamansky** [comment]
Could you please attach sample app which can be compiled. I can't assemble working program from this snippets (

**Comment by dengdui-ganan** [comment]
[achilles.tar.gz](https://github.com/Softmotions/iowow/files/4367085/achilles.tar.gz)
please use  bazel build

**Comment by adamansky** [comment]
Take a look to https://github.com/pmwkaa/ioarena benchmark I will show you good read ops scalability on the following simple benchmark:

```
./ioarena -B set -D iowow -n 4000000
  
time | bench      rps      min       avg       rms       max       vol           #N
    1.000 |   set: 246.268K   2.134us   3.777us   5.124us   1.529ms  11.821Mbps 246.346K
    2.001 |   set: 262.034K   2.165us   3.534us   3.856us 487.874us  12.578Mbps 508.432K
    3.001 |   set: 260.663K   2.186us   3.553us   3.757us  71.409us  12.512Mbps 769.148K
    4.001 |   set: 247.574K   2.125us   3.754us  13.783us   6.531ms  11.884Mbps   1.017M
   ... 
```

**single read thread:**

```
./ioarena -r 1 -c -B get -D iowow -n 4000000

time | bench      rps      min       avg       rms       max       vol           #N
    1.001 |   get: 229.818K   2.149us   4.180us   6.227us   2.037ms  11.031Mbps 229.954K
    2.001 |   get: 235.435K   2.036us   4.079us   4.312us  74.977us  11.301Mbps 465.450K
    3.001 |   get: 237.401K   1.980us   4.044us   4.254us  70.695us  11.395Mbps 702.904K
    4.001 |   get: 236.577K   2.119us   4.059us   4.277us  62.648us  11.356Mbps 939.531K
   ...
```

We have throughput: **233Kops/s** for single thread

**2 read threads:**

```
./ioarena -r 2 -c -B get -D iowow -n 4000000

time | bench      rps      min       avg       rms       max       vol           #N
    1.001 |   get: 372.963K   2.327us   5.183us   7.183us   1.995ms  17.902Mbps 373.205K
    2.001 |   get: 374.633K   2.463us   5.161us   5.500us 129.935us  17.982Mbps 747.950K
    3.001 |   get: 369.513K   2.375us   5.235us   5.462us 108.908us  17.737Mbps   1.118M
    4.002 |   get: 374.413K   2.423us   5.167us   5.431us 476.080us  17.972Mbps   1.492M
   ...
```
We have throughput: **370Kops/s** for 2 reading threads


**4 read threads:**
```
time | bench      rps      min       avg       rms       max       vol           #N
    1.006 |   get: 431.477K   2.968us   9.027us  10.950us   1.781ms  20.711Mbps 433.953K
    2.012 |   get: 438.610K   3.021us   8.934us   9.522us 166.134us  21.053Mbps 875.178K
    3.014 |   get: 436.676K   2.838us   8.957us   9.563us 160.672us  20.960Mbps   1.313M
    4.023 |   get: 434.864K   3.028us   8.989us   9.384us 153.685us  20.873Mbps   1.752M
   ...
```
We have throughput: **430Kops/s** for 4 reading threads

---- 

I suppose the problem in your code

**Comment by adamansky** [comment]
Anyway I try to do brief review your code trying to find bottleneck point

**Comment by dengdui-ganan** [comment]
Thanks.
I find if i use first key as IWDB(with multi db file) not dbid, than multi thread will not interfered.
if i use key as single IWDB with multi dbid,  read thread will be interfered each other.

**Comment by Dan-Do** [comment]
> Hi! Could you please provide test code. Iowow uses RW locks so has good read scalability on SSD

Hi @adamansky Is it better if you use lock-free skip list? I have the issue when benchmarking `concurrent write` on ioarena
```./ioarena -m sync -D iowow  -B crud  -i yes -n 1000 -r 20 -w 20
total:         7.585Ks             20000
min latency:  47.531ms/op
avg latency: 379.243ms/op
rms latency:  23.597ms/op
max latency:   1.984s /op
 throughput:  52.515 ops/s
```
It seems the issue #39 is true.

**Comment by Dan-Do** [comment]
It's slow when running this `./ioarena -m sync -p -D iowow -B crud -n 100000 -v 128 -r 2 -w 2` on WSL2 SSD
```bash
total:         1.824Ks            200000
min latency:   4.199ms/op
avg latency:   9.119ms/op
rms latency:   9.466ms/op
max latency: 234.065ms/op
 throughput: 219.225 ops/s
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> rusage
iops: read 0, write 15473096, page 1934149
cpu: user 40.285945, system 155.530533
space: disk 64.003906, ram 0.058426
```

**Comment by adamansky** [comment]
> It's slow when running this `./ioarena -m sync -p -D iowow -B crud -n 100000 -v 128 -r 2 -w 2` on WSL2 SSD
> 
> ```shell
> total:         1.824Ks            200000
> min latency:   4.199ms/op
> avg latency:   9.119ms/op
> rms latency:   9.466ms/op
> max latency: 234.065ms/op
>  throughput: 219.225 ops/s
> >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> rusage
> iops: read 0, write 15473096, page 1934149
> cpu: user 40.285945, system 155.530533
> space: disk 64.003906, ram 0.058426
> ```

It will be slow until `-m sync` is enabled since after every write op the engine do fs buffers flush

**Comment by Dan-Do** [comment]
> ```shell
./ioarena -m sync -D iowow -c -B crud -i yes -n 1000 -r 20 -w 20
total:        30.721s              39000
min latency:  71.005us/op
avg latency: 787.725us/op
rms latency: 797.458us/op
max latency:   3.233ms/op
 throughput:  24.714Kops/s
> ```
I rerun this benchmark on WSL SSD but the result is different, don't know why
```shell
total:         3.303Ks             39000
min latency:   2.881ms/op
avg latency:  84.696ms/op
rms latency:  19.643ms/op
max latency: 619.222ms/op
 throughput: 230.146 ops/s
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> rusage
iops: read 0, write 2859208, page 357402
cpu: user 8.315216, system 36.287261
space: disk 121.113281, ram 0.061794
```

**Comment by Dan-Do** [comment]
> It will be slow until `-m sync` is enabled since after every write op the engine do fs buffers flush

Yes, it's correct. BTW, I would like to evaluate iowow with other libraries such as `io_uring`, `rpmalloc`. Do you have any internal development docs or any hints to suggest?
