### ISSUE TITLE
how much memory take with 100 million key?

### ISSUE THREAD

**Issue by dengdui-ganan** [Softmotions/iowow#33]
I insert  100million key in iowow with  key 8Byte and Value 192Byte, it will take more than 5G memory.
Why does iowow cost so much memory , is key and offset saved in memory?

**Comment by adamansky** [comment]
It is virtual mmaped memory cached by OS, not actual used by engine

**Comment by dengdui-ganan** [comment]
i top pid as follows:
![K20200325-211352](https://user-images.githubusercontent.com/62244377/77540176-9384c080-6edd-11ea-9a1b-516886fba965.png)

the engine will really cost memory not virtual memory

**Comment by dengdui-ganan** [comment]
I open the db with options:
`iw_opts.wal.enabled = false;
 iw_opts.fmt_version = 0;
 iw_opts.oflags = 0;`

and insert with flag 0,
`iwrc status = iwkv_put(*db, &iw_key, &iw_val, 0);`

**Comment by adamansky** [comment]
RSS is the Resident Set Size and is used to show how much memory is allocated to that process and is in RAM. It does not include memory that is swapped out. It does include memory from shared libraries as long as the pages from those libraries are actually in memory. It does include all stack and heap memory.

If I correctly understand: `mmaped` set of touched (durty) pages accounted in RSS. OS will flush this pages on disk at some point in time in future (example: trying to get free physical memory for another task)  and RSS will be decreased.

**Comment by adamansky** [comment]
In order to limit RSS if you really need this you can activate WAL by the price of reducing write performance by factor of `x2`

**Comment by dengdui-ganan** [comment]
Enable wal will core dump and  there has core info because 
I build the library in gcc4.9.2 and use in gcc4.8.5。 
`iw_opts.wal.enabled = true; iw_opts.fmt_version = 0; iw_opts.oflags = 0;`

**Comment by adamansky** [comment]
> Enable wal will core dump and there has core info because
> I build the library in gcc4.9.2 and use in gcc4.8.5。
> `iw_opts.wal.enabled = true; iw_opts.fmt_version = 0; iw_opts.oflags = 0;`
Thanks.
Bad news =) If you have minimal workable app which cause this crash please send me it adamansky @ gmail.com

**Comment by dengdui-ganan** [comment]
`#include "iwkv.h"

int main() {
    iw_init();
    
    IWKV* iwkv = new IWKV();
    IWKV_OPTS iw_opts;
    iw_opts.path = "test_db";
    iw_opts.wal.enabled = true;
    iw_opts.fmt_version = 0;
    iw_opts.oflags = IWKV_TRUNC;

    iwkv_open(&iw_opts, iwkv);
    IWDB* db = new IWDB();
    iwkv_db(*iwkv, 1, 0, db);

    IWKV_val iw_key, iw_val;
    while (true) {
        for (int32_t i = 0; i < 1000000; ++i) {
            iw_key.data = (void*)(&i);
            iw_key.size = sizeof(int32_t);

            iw_val.data = (void*)(&i);
            iw_val.size = sizeof(int32_t);

            iwkv_put(*db, &iw_key, &iw_val, 0);
        }
    }
    return 0;
}
`
This time can get core info:
![wal](https://user-images.githubusercontent.com/62244377/77547585-583bbf00-6ee8-11ea-9520-6fdd70717a50.png)

**Comment by adamansky** [comment]
Please do:
```
IWKV_OPTS iw_opts;
memset(&iw_opts, 0, sizeof(iw_opts))
...
```
Let me know about result of this fix

**Comment by dengdui-ganan** [comment]
Thank you very much!
It will not core anymore and the memory can refresh normally!

**Comment by adamansky** [comment]
Good
