### ISSUE TITLE
Feature: Compaction

### ISSUE THREAD

**Issue by doublex** [Softmotions/iowow#34]
Is there a chance to "compact" `iwkv` database, e.g. to reduce the file-size?

**Comment by adamansky** [comment]
Hi @doublex Do you mean perform data file defragmentation? Here is the only way to do it - recreate and reimport whole database using standard API. Not so convenient although. I may add dedicated API function doing it but don't promise any timeframes.

**Comment by doublex** [comment]
Thanks.
Excellent work
