### ISSUE TITLE
bug: _fsm_set_bit_status_lw

### ISSUE THREAD

**Issue by Jin10Dong** [Softmotions/iowow#36]
i allocate by the following steps: 
0, offset: 0; length: 1;
1, offset: 1; length: 3;
2, offset: 4; length: 3;
3, offset: 7; length: 3;
... Repeat this allocation, the error occurs at 
42, offset: 127; length: 3;
bitmap[16]=1; 
but it should be 3.

**Comment by adamansky** [comment]
Hi Jin Dong! Thank you for report! Will check it shortly!

**Comment by adamansky** [comment]
@Jin10Dong Could you please provide a simple test case?

**Comment by Jin10Dong** [comment]
I am very sorry.
I reexamined my code and found that an extra operation on bitmap caused the above error.

**Comment by adamansky** [comment]
Thank you! @Jin10Dong
