### ISSUE TITLE
can you provide compare to level for benchmark data 

### ISSUE THREAD

**Issue by perrynzhou** [Softmotions/iowow#37]
i can't found benchmark data compare to leveldb? there is no any data for comparing to leveldb.https://iowow.io/articles/intro/benchmark_results.html

**Comment by perrynzhou** [comment]
@all i think it's performance less than leveldb.no any data to prove iowow is good performance than leveldb.at the same time,if disable transactio for wiredtiger,may wiredtiger's performance is good than iowow.

**Comment by adamansky** [comment]
Hi! Look into https://github.com/pmwkaa/ioarena

**Comment by perrynzhou** [comment]
@adamansky  i don't why close that.can you provide performance data for compare leveldb and iowow
