### ISSUE TITLE
Usage of basename()/basename_r() in src/log/iwlog.c

### ISSUE THREAD

**Issue by danfe** [Softmotions/iowow#4]
Currently, in `_default_logfn()` function, `basename()` usage could be problematic, for two reasons:
* Standard version of its definition is `char *basename(char *path);` but you pass `file` argument which is declared as `const char *file`, which in turn upsets strict compilers (they generate warning) and essentially devoids `file` string from being constant after the call to `basename()` (this is not specific to any particular operating system);
* Another problem is with BSD-specific reentrant `basename_r()` function.  Originally it was introduced because in FreeBSD, the `basename()` function used to return a pointer to internal storage space allocated on the first call that would be overwritten by subsequent calls.  This was not thread-safe, so `basename_r()` was added which accepted user-provided buffer to store the result.  In FreeBSD 12.0, this function was reimplemented to store its result in the provided input buffer, and `basename_r()` was removed.  Thus, this code would not build on the FreeBSD versions 12+.  If the code can guarantee that it could not be called simultaneously from different threads, the easiest way would be just to always use `basename()` across all operating systems.

**Comment by adamansky** [comment]
Yes,  `basename_r` used for `FreeBSD` because of its thread safety, since no one can guarantee  calls of `basename()` from other threads. May be It will better to use `basename` for FreeBSD 12 and higher and `basename_r` for older versions?

**Comment by danfe** [comment]
I have a better idea.  Instead of trying to guess which OSes have `basename_r()` why not simply ask CMake to detect it?

I've just tested something like this and it works (this is not a real patch, I've just copy-pasted some relevant parts, it might not apply directly):

``` diff
--- src/CMakeLists.txt.orig
+++ src/CMakeLists.txt
@@ -21,6 +21,7 @@ endif()
 include(CheckIncludeFile)
 include(CheckIncludeFiles)
 include(CheckLibraryExists)
+include(CheckFunctionExists)
 include(TestBigEndian)

 if ((CMAKE_BUILD_TYPE EQUAL Release) OR (CMAKE_BUILD_TYPE EQUAL RelWithDebInf
o))
@@ -52,6 +53,11 @@ if (NOT WIN32)
     list(APPEND PROJECT_LLIBRARIES ${CMAKE_THREAD_LIBS_INIT})
 endif()

+check_function_exists(basename_r HAVE_BASENAME_R)
+if (HAVE_BASENAME_R)
+    set_source_files_properties(log/iwlog.c PROPERTIES COMPILE_FLAGS -DHAVE_BASENAME_R)
+endif()
+
 find_library(M_LIB m)
 if (NOT M_LIB)
        message(FATAL_ERROR "Library 'libm' not FOUND")
--- src/log/iwlog.c.orig	2018-04-12 13:48:26 UTC
+++ src/log/iwlog.c
@@ -383,7 +383,7 @@ static iwrc _default_logfn(locale_t locale,
     ecode_msg = _ecode_explained(locale, ecode);
   }
 
-#if defined(__APPLE__) || defined(__FreeBSD__)
+#ifdef HAVE_BASENAME_R
   char bfile[MAXPATHLEN];
   if (file && line > 0) {
     file = basename_r(file, bfile);

```

**Comment by adamansky** [comment]
Fixed using `check_symbol_exists(basename_r libgen.h HAVE_BASENAME_R)`

**Comment by danfe** [comment]
You only fixed the second problem, but not the first one (you still pass `const char *` to function that wants `char *` and actually modifies its contents in some implementations).  This issue was closed prematurely.

**Comment by adamansky** [comment]
Sure, you are right)

**Comment by adamansky** [comment]
Fixed
