### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by openwrtfirmwarecostum** [Softmotions/iowow#45]
@adamansky 

`[  2%] Creating directories for 'extern_iowow'
[  5%] Performing download step (download, verify and extract) for 'extern_iowow'
-- Downloading...
   dst='/home/ubuntu/jail/build_dir/target-aarch64_cortex-a53_musl/node-ejdb2_node-2.62.5/ejdb2-nodeisCmFR/ejdb-f145e092534e4e1f93a9b14572e5636ddc8d1c2b/build/src/iowow.zip'
   timeout='360 seconds'
   inactivity timeout='none'
-- Using src='https://github.com/Softmotions/iowow/archive/master.zip'
-- Retrying...
-- Using src='https://github.com/Softmotions/iowow/archive/master.zip'
-- Retry after 5 seconds (attempt #2) ...
-- Using src='https://github.com/Softmotions/iowow/archive/master.zip'
-- Retry after 5 seconds (attempt #3) ...
-- Using src='https://github.com/Softmotions/iowow/archive/master.zip'
-- Retry after 15 seconds (attempt #4) ...
-- Using src='https://github.com/Softmotions/iowow/archive/master.zip'
-- Retry after 60 seconds (attempt #5) ...
-- Using src='https://github.com/Softmotions/iowow/archive/master.zip'
CMake Error at extern_iowow-stamp/download-extern_iowow.cmake:170 (message):
  Each download failed!

    error: downloading 'https://github.com/Softmotions/iowow/archive/master.zip' failed
          status_code: 6
          status_string: "Couldn't resolve host name"
          log:
          --- LOG BEGIN ---
          getaddrinfo(3) failed for github.com:443

  Couldn't resolve host 'github.com'

  Closing connection 0

  

          --- LOG END ---
          error: downloading 'https://github.com/Softmotions/iowow/archive/master.zip' failed
          status_code: 6
          status_string: "Couldn't resolve host name"
          log:
          --- LOG BEGIN ---
          getaddrinfo(3) failed for github.com:443

  Couldn't resolve host 'github.com'

  Closing connection 0`

**Comment by adamansky** [comment]
Obviously you cannot download https://github.com/Softmotions/iowow/archive/master.zip

Check this out: https://github.com/Softmotions/ejdb/issues/342
