### ISSUE TITLE
Can provide macro to define tmp dir or others ways for define tmp dir?

### ISSUE THREAD

**Issue by blueshame** [Softmotions/iowow#47]
Some OS maybe does not has [P_tmpdir](https://github.com/Softmotions/iowow/blob/c701a7b3d20fa4a0496ce1b11c1e4d00bd61660e/src/platform/unix/unix.c#L380), SO when this dir does not exists, some time will meet **IW_ERROR_NOT_EXISTS** error. Can provide macro to define tmp dir or others ways for define tmp dir? 

I have to change the code like below

```C
size_t iwp_tmpdir(char *out, size_t len) {
#ifdef IOWOW_TMP_PATH
  const char *tdir = IOWOW_TMP_PATH
  size_t tlen = strlen(IOWOW_TMP_PATH);
#else
  const char *tdir = P_tmpdir;
  size_t tlen = strlen(P_tmpdir);
#endif
  size_t nw = MIN(len, tlen);
  memcpy(out, tdir, nw);
  return nw;
}
```

**Comment by blueshame** [comment]
@adamansky Can you provide some way to do this?

**Comment by adamansky** [comment]
It should be OK now I hope https://github.com/Softmotions/iowow/commit/daafac9c60a560228967e448f28a5ab1049a9f56
