### ISSUE TITLE
Compiler warning: ‘snprintf’ output may be truncated before the last format character [-Wformat-truncation=]

### ISSUE THREAD

**Issue by AlbertoGP** [Softmotions/iowow#51]
~This does not cause any issues in practice, it’s just about removing the warning.~

```
‘snprintf’ output may be truncated before the last format character [-Wformat-truncation=]
note: 'snprintf' output between 7 and 8 bytes into a destination of size 7
```

The warning is for [line 625 in `json/iwjson.c`](https://github.com/Softmotions/iowow/blob/89b5e63d69126d1fe8ba8961c25174bf6ac3c49f/src/json/iwjson.c#L625): `snprintf(sbuf, 7, "\\u%04X", cp);`
```
      char sbuf[7]; // escaped unicode seq
      utf8proc_int32_t cp;
…
      if (cp > 0x0010000UL) {
…
      } else {
        snprintf(sbuf, 7, "\\u%04X", cp);
        PT(sbuf, 6, 0, 0);
      }
```

~What the compiler (tested `gcc 10.2.1` and `11.2.0`) means is that `utf8proc_int32_t` `cp` could in theory be negative which would make the output be 7 characters plus the zero terminator. That is wrong of course, the actual problem is that `%X` requires `unsigned int` values. In practice if `cp` is `-1` you will get `\uFFFF` and not `\u-000` after calling `PT(sbuf, 6, 0, 0);`.~

~`utf8proc` uses the value `-1` for errors and for grapheme breaks (https://github.com/JuliaStrings/utf8proc/blob/master/utf8proc.c#L206). I am not sure whether this means that `cp` could become `-1` even with valid input.~

~I would prefer to modify `utf8proc` to use unsigned integers instead, with `0xFFFFFFFF` as sentinel value instead of `-1`, but the simplest solution is to cast the value in line `625` to `uint32_t`:~
```
        snprintf(sbuf, 7, "\\u%04X", (uint32_t) cp & 0x0000FFFF);
```

~If you would like to modify the embedded copy of `utf8proc` to use unsigned integers I will be happy to prepare a PR, but I guess that you might prefer to keep it unmodified since it is an external library.~

**Comment by AlbertoGP** [comment]
The warning goes away in a simpler way if we replace `if (cp > 0x0010000UL) {` with `if (cp >= 0x0010000UL) {`, which I think is what was intended.

**Comment by adamansky** [comment]
Thank you! Merged
