### ISSUE TITLE
murmurhash3 needs a fix for Big-endian

### ISSUE THREAD

**Issue by barracuda156** [Softmotions/iowow#55]
@adamansky Maybe either of these can be used?

https://github.com/hideo55/node-murmurhash3/blob/master/src/MurmurHash3.cpp

https://github.com/adrianeboyd/murmurhash/blob/bugfix/big-endian-3/murmurhash/MurmurHash3.cpp

Currently the test case for it fails, unsurprisingly: https://github.com/Softmotions/iowow/issues/54

**Comment by adamansky** [comment]
I'm considering wyhash to replace murmur so more likely will do it

**Comment by barracuda156** [comment]
Sounds good, thank you!
